### ISSUE TITLE
Insert Icon + Text 

### ISSUE THREAD

**Issue by vaporwavie** [MiLeung/top-bar-nav#1]
Hello!

Does this navbar allows the inclusion of Icon + Text on the items?

Thanks :)

**Comment by mileung** [comment]
Not both at the same time, but I'm open to pull requests. It'd be a good idea to have a `component` key as a routeStack object config, so you can render any react native component for the "label".

**Comment by vaporwavie** [comment]
Hmmmm... Okay! Gonna play around with it a lilttle. On any luck, I'll open a PR here. Thanks for answering!
